apiVersion: v1
kind: Service
metadata:
  name: simple-todo-canary
spec:
  selector:
    app: simple-todo-canary # label of stable pods
    version: canary
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Pod container port
      nodePort: 30002 # NodePort for accessing from outside
  type: NodePort
