apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-todo
  template:
    metadata:
      labels:
        app: simple-todo
    spec:
      containers:
      - name: simple-todo
        image: simple-todo:latest
        ports:
        - containerPort: 80
