apiVersion: v1
kind: Service
metadata:
  name: simple-todo-service
spec:
  type: NodePort
  selector:
    app: simple-todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
