apiVersion: v1
kind: Service
metadata:
  name: simple-todo-stable
spec:
  selector:
    app: simple-todo # label of stable pods
    version: stable
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Pod container port
      nodePort: 30001 # NodePort for accessing from outside
  type: NodePort
